### ISSUE TITLE
Double-Riff and Desync Bug

### ISSUE THREAD

**Issue by asbestosbill** [spaceribs/plopdown#14]
I have screencapture videos of this bug [on Google Drive](https://drive.google.com/drive/folders/1TCkZveW8cGOjXWndi8KewQyEBSx3wW8r?usp=sharing) (there's no part 1 because I didn't think to start recording until I encountered the error).

While testing Equilibrium in Firefox 76.0.1 on Windows 10, I clicked on the Plopdown logo overlaid on the video, and after that point, I could no longer mute the riff. I paused the movie, but the riff kept playing, causing the sync to be lost. Skipping around with the Netflix playback bar, the riff would jump ahead or backwards too, keeping them out of sync. ('pt2')

After refreshing the page ('pt3') and reloading the riff through the Plopdown extension, the sync was still off, and there were two copies of the riff playing on top of each other, creating a reverb effect. I could, however, mute ONE of the tracks by clicking the volume icon.

Restarting Firefox and my PC did not change anything ('pt4), but I did find that I could restore the sync by starting the movie from the beginning. I was only able to fix the issues by removing and reinstalling the Plopdown extension ('pt5'), although when I did that, I did notice that the QuipTracks Equilibrium track somehow got added twice, resulting in doubled audio until I deleted one of them, so it's possible I could have done that without reinstalling. I also noticed that the Plopdown extension menu shows two videos once the track is loaded — "Netflix" and "QuipTracks Equilibrium."

**Comment by spaceribs** [comment]
Thanks for all the details, that video is extremely helpful for tracking this bug down. I'm going to investigate but I assume that the issue is that you accidentally attached your riff to the playing riff, and experienced some riffception 🤯

Attaching to videos created by the plugin is obviously something we probably should filter out. The next time this occurs, you can go to the options page and hit the reset button to clear out all references you've collected.
